version: "2.31"
services:
  pharmacy-recommendation-redis:
    container_name: fc-pharmacy-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: hooney200/fc-pharmacy-recommendation-redis
    ports:
      - "6379:6379"
  pharmacy-recommendation-database:
    container_name: fc-pharmacy-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: hooney200/fc-pharmacy-recommendation-database
    environment:
      - MARIADB_DATABASE=pharmacy-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"